on: [push]

jobs:
  gofw_job:
    runs-on: ubuntu-latest
    name: Run gofw
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Create go executable
        env:
          GOOS: linux
        run: go build -o release/gofw ./cmd/main.go
      - name: Run test
        id: gofw-test
        uses: ./
